name: "load-testing"

services:
  grafana:
    image: grafana/grafana:12.0.2
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    env_file:
      - ./grafana/config.monitoring
    ports:
      - '127.0.0.1:3000:3000'
    restart: unless-stopped
    user: "472"

  prometheus:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - '127.0.0.1:9090:9090'
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:
