# https://grafana.com/blog/2024/07/15/performance-testing-with-grafana-k6-and-github-actions/
name: Scenario run
run-name: K6 run scenario by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Service hostname'
      scenario:
        required: true
        description: 'Scenario path ex: service-name/smoke-test-home-page.js'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: scenarios/${{ inputs.scenario }}
          flags: -e HOST=${{ inputs.host }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary-report
          path: html-report.html
